config/routes.rb
Scanhandler::Application.routes.draw do
  match "users/inactive" => "root#inactive"
  authenticated :user do
    root :to => 'root#index'
  end
  devise_scope :user do
  	root :to => "devise/sessions#new"
  end
  devise_for :users, :skip => [:registrations], :controllers => { :invitations => 'users/invitations' }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users
  match "people/search" => "people#search"
  resources :people do
    resources :scans, only: [:create, :destroy]
    resources :person_notes, only: [:create, :destroy]
  end
  match "scans/:id" => "scans#download", via: :get, as: :download_scan
  match "scans/:id" => "scans#destroy", via: :delete, as: :destroy_scan
end

app/models/person.rb
require 'csv'
require 'rails/all'

class Person < ActiveRecord::Base
  has_many :people_first_name_trigrams, dependent: :destroy
  has_many :people_last_name_trigrams, dependent: :destroy
  has_many :scans, order: 'scan_date DESC', dependent: :destroy
  has_many :person_notes, order: 'created_at DESC', dependent: :destroy
  belongs_to :user # user that created this person
  attr_accessible :first_name, :last_name, :cal_south_id
  validates :first_name, presence: true, length: { maximum: 64 }
  validates :last_name, presence: true, length: { maximum: 64 }
  validates :cal_south_id, uniqueness: true, allow_blank: true

  after_save :handle_saved

  def self.search(first_name , last_name, is_fuzzy = false, include_nicknames = false)
    if last_name.nil? && first_name.nil?
      return includes(:scans).order(:last_name)
    end

    # handle fastest search with a special case
    if !is_fuzzy && !include_nicknames
      if !first_name.nil?
        if !last_name.nil?
          first_name.downcase!
          last_name.downcase!
          return includes(:scans).where("lower(first_name) like lower(:first_name) and lower(last_name) like lower(:last_name)",
                         {first_name: first_name + '%', last_name: last_name + '%'} )
        else
          first_name.downcase!
          return includes(:scans).where("lower(first_name) like lower(:search)", {search: first_name + '%'} ).order("char_length(first_name)")
        end
      else
        last_name.downcase!
        return includes(:scans).where("lower(last_name) like lower(:search)", {search: last_name + '%'} ).order("char_length(last_name)")
      end
    end

    people_by_first_name = []
    people_by_first_name_with_nicknames = []
    people_by_first_name_with_nicknames_fuzzy = []
    people_by_first_name_fuzzy = []
    people_by_last_name = []

    if !last_name.nil?
      last_name.downcase!
      people_by_last_name = includes(:scans).where("lower(last_name) like lower(:search)", {search: last_name + '%'} ).order("char_length(last_name)").to_a
      if is_fuzzy
        people_by_last_name |= get_fuzzy_last_name_matches(last_name)
      end
    end

    if !first_name.nil?
      first_name.downcase!
      people_by_first_name = includes(:scans).where("lower(first_name) like lower(:search)", {search: first_name + '%'} ).order("char_length(first_name)")
      if is_fuzzy
        people_by_first_name_fuzzy = get_fuzzy_first_name_matches(first_name)
      end

      if include_nicknames && first_name.length > 2
        first_names = []
        name_groups = []
        nicknames = Nickname.search(first_name, is_fuzzy)
        nicknames.each do |nickname|
          p nickname.name
          first_names_from_nicknames |= nickname.name
          name_groups |= [nickname.name_group]
        end

        first_names_from_nicknames = []
        name_groups.each do |name_group|
          first_names_from_nicknames |= name_group.names.split(',')
        end

        first_names_from_nicknames.each do |first_name_from_nicknames|
          people_by_first_name_with_nicknames |= includes(:scans).find_all_by_first_name(first_name_from_nicknames)
          if is_fuzzy
            people_by_first_name_with_nicknames_fuzzy |= get_fuzzy_first_name_matches(first_name_from_nicknames)
         end
        end
      end
    end

    result = nil
    if !first_name.nil?
      result = people_by_first_name |
          people_by_first_name_with_nicknames |
          people_by_first_name_fuzzy |
          people_by_first_name_with_nicknames_fuzzy
      if !last_name.nil?
        result &= people_by_last_name
      end
    else
      result = people_by_last_name
    end
    result
  end

  protected
  def handle_saved
    PeopleFirstNameTrigram.delete_all(:person_id => self.id)
    word = ' ' + self.first_name.downcase
    (0..word.length-3).each do |idx|
      tg = word[idx,3]
      self.people_first_name_trigrams.create(tg: tg);
    end

    PeopleLastNameTrigram.delete_all(:person_id => self.id)
    word = ' ' + self.last_name.downcase
    (0..word.length-3).each do |idx|
      tg = word[idx,3]
      self.people_last_name_trigrams.create(tg: tg);
    end
  end

  private
  def self.get_fuzzy_first_name_matches(first_name)
    first_name = " #{first_name} "
    limit = 20
    trigram_list = (0..first_name.length-3).collect { |idx| first_name[idx,3] }
    sql = 'select *
           from people
           inner join(
             select person_id, count(person_id) as score
             from people_first_name_trigrams
             where tg in (?)
             group by person_id
             having count(person_id) > 2
             order by score desc
             limit ' + limit.to_s + ') as scored_person_first_names
           on people.id = scored_person_first_names.person_id'
    people = Person.includes(:scans)
    people = people.find_by_sql([sql, trigram_list])
    people
  end

  def self.get_fuzzy_last_name_matches(last_name)
    last_name = " #{last_name} "
    limit = 20
    trigram_list = (0..last_name.length-3).collect { |idx| last_name[idx,3] }
    sql = 'select *
           from people
           inner join(
             select person_id, count(person_id) as score
             from people_last_name_trigrams
             where tg in (?)
             group by person_id
             having count(person_id) > 2
             order by score desc
             limit ' + limit.to_s + ') as scored_person_last_names
           on people.id = scored_person_last_names.person_id'
    people = Person.includes(:scans)
    people = people.find_by_sql([sql, trigram_list])
    people
  end

  def self.to_csv
    CSV.generate do |csv|
        csv <<  ["First Name", "Last Name", "Cal South Id", "Date Added", "Added By", "Date of Last Scan"]
        all.each do |person|
        scans = person.scans
        csv << [person.first_name,
                      person.last_name,
                      person.cal_south_id || "",
                      person.created_at.to_date,
                      person.user.name || person.user.email,
                      scans.count > 0 ? scans.first.scan_date.to_date : 'NO SCAN!']
      end
    end
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :read, Person, :message => 'Not authorized to view person information.'
    respond_to do |format|
      format.html
      format.csv do
        @people = Person.order(:last_name)
        render text: @people.to_csv
      end
      format.xls do
        @people = Person.order(:last_name)
      end
    end
  end

  def search
    authorize! :read, Person, :message => 'Not authorized to view person information.'
    first_name = params[:first_name].strip
    last_name = params[:last_name].strip
    @people = Person.search(first_name.empty? ? nil : first_name,
                            last_name.empty? ? nil : last_name,
                            true,
                            true)
    render partial: 'people/search'
  end

  def new
    authorize! :create, Person, :message => 'Not authorized to create person information.'
    @person = Person.new(first_name: params[:first_name].strip, 
                         last_name: params[:last_name].strip,
                         cal_south_id: params[:cal_south_id].try(:strip))
  end

  def create
    authorize! :create, Person, :message => 'Not authorized to create person information.'
    @person = Person.new(params[:person])
    @person.cal_south_id = nil if @person.cal_south_id.strip.blank?
    @person.user_id = current_user.id
    if @person.save
      redirect_to @person
    else
      render 'new'
    end
  end

  def show
   authorize! :read, Person, :message => 'Not authorized to view person information.'
   @person = Person.includes(:scans).includes(:person_notes).find(params[:id])
   @scan = Scan.new
   @first_name = @person.first_name
   @last_name = @person.last_name
   @person_note = PersonNote.new
 end

  def update
    authorize! :update, Person, :message => 'Not authorized to modify person information.'
   @person = Person.includes(:scans).includes(:person_notes).find(params[:id])
    if @person.nil?
      redirect_to people_path, :alert => "Person does not exist"
    else
      @scan = Scan.new
      @first_name = @person.first_name
      @last_name = @person.last_name
      @person_note = PersonNote.new
      if !@person.update_attributes(first_name: params[:person][:first_name].strip,
                                    last_name: params[:person][:last_name].strip,
                                    cal_south_id: params[:person][:cal_south_id].strip)
        flash.now[:alert] = 'Error updating person.  See errors below.'
        render 'show'
      else
        @first_name = @person.first_name
        @last_name = @person.last_name
        flash.now[:notice] = 'Person successfully updated'
        render 'show'
      end
    end
  end

  def destroy
    authorize! :destroy, Person, :message => 'Not authorized to delete person information.'
    person = Person.find(params[:id])
    person.destroy
    redirect_to people_path, :notice => "Person deleted."
  end
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/people/_new_form.html.erb
<%= simple_form_for @person do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :cal_south_id %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/people/_person.html.erb
<li>
  <%= link_to "#{person.first_name} #{person.last_name}", person %>
</li>

app/views/people/_search.html.erb
<% if @people.count > 0 %>
  <h4>Lookup matches:</h4>
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Cal South Id</th>
        <th>Scan Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.cal_south_id || "" %></td>
        <td><%= person.scans.count > 0 ? ('<span class="label label-success">' + person.scans.first.scan_date.to_date.to_s + '</span>').html_safe : '<span class="label label-important">NO SCAN!</span>'.html_safe %></td>
        <td>
          <%= link_to person, 
                      title: "View info and live scan forms",
                      class: "btn" do %>
            <i class="icon-list"></i>
          <% end %>
          <% if can? :destroy, person %>
            <%= link_to person,
                        confirm: 'Are you sure you want to delete this person?', 
                        method: :delete,
                        title: "Delete this person",
                        class: "btn btn-danger" do %>
              <i class="icon-remove icon-white"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <h4>No matches</h4>
<% end %>

app/views/people/index.html.erb
<h3>Person Lookup</h3>
<% person = Person.new %>

<p>
  Download all:
  <%= link_to "CSV", people_path(format: "csv") %> |
  <%= link_to "Excel", people_path(format: "xls") %>
</p>

<%= form_tag(people_search_path, method: :get, id: "person-search-form", class: "form-inline" ) do %>
    <%= text_field_tag :first_name, nil, autocomplete: "off", class: "input-medium", placeholder: "First Name" %>
    <%= text_field_tag :last_name, nil, autocomplete: "off", class: "input-medium", placeholder: "Last Name" %>
    <%= link_to '#', class: "btn btn-primary",
                     id: "add_new_person_button",
                     base_path: new_person_path do %>
      Add new
    <% end %>
<% end %>
<div id="person_spinner" class="hidden">
  <%= image_tag('spinner.gif') %>
</div>
<div id="person-search-results"></div>

app/views/people/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">First Name</Data></Cell>
        <Cell><Data ss:Type="String">Last Name</Data></Cell>
        <Cell><Data ss:Type="String">Cal South Id</Data></Cell>
        <Cell><Data ss:Type="String">Date Added</Data></Cell>
        <Cell><Data ss:Type="String">Added By</Data></Cell>
        <Cell><Data ss:Type="String">Last Scan Date</Data></Cell>
      </Row>
    <% @people.each do |person| %>
      <Row>
        <Cell><Data ss:Type="String"><%= person.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= person.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= person.cal_south_id || "" %></Data></Cell>

        <Cell><Data ss:Type="String"><%= person.created_at.to_date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= person.user.name || person.user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= person.scans.count > 0 ? person.scans.first.scan_date.to_date : "NO SCAN!" %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/people/new.html.erb
<h1>Add New Person</h1>

<div class="row">
  <div class="span 4">
    <%= render 'people/new_form' %>
  </div>
</div>

app/views/people/show.html.erb
<h2 class="one_line"><%= "#{@first_name} #{@last_name}" %> <small>(Cal South ID: <%= @person.cal_south_id || 'Unknown'%>)</small>
  <% if can? :edit, Person %>
       <button type="button" class="btn one_line" data-toggle="collapse" data-target="#edit_person_collapsible, #edit_blah" title="Edit">
          <i class="icon-pencil"></i>
        </button>
  <% end %>
<h2>
<% if can? :edit, Person %>
   <%= @person.errors.count > 0 ?
            '<div id="edit_person_collapsible" class="collapse in">'.html_safe:
            '<div id="edit_person_collapsible" class="collapse">'.html_safe %>
      <%= simple_form_for @person,
          url: person_path(@person),
          method: 'put',
          multipart: true,
          html: {class: 'form-inline'} do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :cal_south_id , label: "Cal South Id" %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
<% end %>

<h4><%= "Added on #{@person.created_at.to_date} by #{@person.user.name || @person.user.email}" %></h4>
  <legend>Scans
    <% if can? :create, Scan %>
      <button type="button" class="btn" data-toggle="collapse" data-target="#add_scan_collapsible">
        <i class="icon-plus"></i> add
      </button>
    <% end %>
  </legend>
  <% if can? :create, Scan %>
    <%= @scan.errors.count > 0 ?
            '<div id="add_scan_collapsible" class="collapse in">'.html_safe:
            '<div id="add_scan_collapsible" class="collapse">'.html_safe %>
      <%= simple_form_for @scan,
          url: person_scans_path(@person),
          method: 'post',
          multipart: true,
          html: {class: 'form-inline'} do |f| %>
        <%= f.input :scan_date, as: :string, label: "Date of scan" %>
        <%= f.input :image, as: :file , label: "Image file (PDF, jpg, tif, or png.  PDF preferred.)" %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  <% end %>
  <% if !@person.scans.nil? && @person.scans.count > 0 %>
  <table class="table table-condensed table-hover">
    <thead>
      <th>Date Scanned</th>
      <th>Date Scan Submitted</th>
      <th>Added By</th>
      <th></th>
    </thead>
    <tbody>
      <% @person.scans.each do |scan| %>
          <tr>
            <td><%= scan.scan_date %></td>
            <td><%= scan.created_at.to_date %></td>
            <td><%= scan.user.name.nil? ? scan.user.email : scan.user.name %></td>
            <td><%= link_to Rails.env == 'production' ? scan.download_url : download_scan_path(scan),
                            title: "Download scan PDF",
                            class: "btn" do %>
                  <i class="icon-download-alt"></i> pdf
                <% end %>
                <% if can? :destroy, Scan %>
                  <%= link_to destroy_scan_path(scan),
                              confirm: 'Are you sure you want to delete this scan?',
                              method: :delete,
                              title: "Delete this scan",
                              class: "btn btn-danger" do %>
                    <i class="icon-remove icon-white"></i>
                  <% end %>
                <% end %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
  <legend>Notes
    <% if can? :create, PersonNote %>
      <button type="button" class="btn" data-toggle="collapse" data-target="#add_note_collapsible">
        <i class="icon-plus"></i> add
      </button>
    <% end %>
  </legend>
<% if can? :create, PersonNote %>
    <%= @person_note.errors.count > 0 ?
            '<div id="add_note_collapsible" class="collapse in">'.html_safe:
            '<div id="add_note_collapsible" class="collapse">'.html_safe %>
      <%= simple_form_for @person_note,
          url: person_person_notes_path(@person),
          method: 'post',
          multipart: true,
          html: {class: 'form-inline'} do |f| %>
        <%= f.input :text, as: :text, input_html: {rows: 10, class: "span12 tinymce" }, label: "Note:" %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>

    <script type="text/javascript">
tinymce.init({
        selector: "textarea.tinymce",
        plugins: [
                "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                "table contextmenu directionality emoticons template textcolor paste fullpage textcolor"
        ],

        toolbar1: "newdocument fullpage | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect",
        toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image media code | inserttime preview | forecolor backcolor",
        toolbar3: "table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | spellchecker | visualchars visualblocks nonbreaking template pagebreak restoredraft",

        menubar: false,
        toolbar_items_size: 'small',

        style_formats: [
                {title: 'Bold text', inline: 'b'},
                {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                {title: 'Example 1', inline: 'span', classes: 'example1'},
                {title: 'Example 2', inline: 'span', classes: 'example2'},
                {title: 'Table styles'},
                {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ],

        templates: [
                {title: 'Test template 1', content: 'Test 1'},
                {title: 'Test template 2', content: 'Test 2'}
        ]
});</script>

  <% end %>
  <% if !@person.person_notes.nil? && @person.person_notes.count > 0 %>
    <% @person.person_notes.each do |person_note| %>
       <div class="container-fluid">
       <div class="row-fluid">
          <span class="label"><%= person_note.created_at %></span> by <span class="label"><%= person_note.user.name.nil? ? person_note.user.email : person_note.user.name %></span>
        </div>
        <div class="row-fluid">
          <div class="well well-small"><%= person_note.text.html_safe %></div>
        </div>
      </div>
  <% end %>
<% end %>