config/routes.rb
Scanhandler::Application.routes.draw do
  match "users/inactive" => "root#inactive"
  authenticated :user do
    root :to => 'root#index'
  end
  devise_scope :user do
  	root :to => "devise/sessions#new"
  end
  devise_for :users, :skip => [:registrations], :controllers => { :invitations => 'users/invitations' }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users
  match "people/search" => "people#search"
  resources :people do
    resources :scans, only: [:create, :destroy]
    resources :person_notes, only: [:create, :destroy]
  end
  match "scans/:id" => "scans#download", via: :get, as: :download_scan
  match "scans/:id" => "scans#destroy", via: :delete, as: :destroy_scan
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { maximum: 64 }


  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :send_notification, :as => :admin
  attr_accessible :name, :send_notification, :email, :password, :password_confirmation, :remember_me

  has_many :people
  has_many :scans
  has_many :person_notes
 end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_filter :authenticate_user!

  def after_invite_path_for(resource)
    users_path
  end

  def after_accept_path_for(resource)
    people_path
  end

  def create
    authorize! :create, User, :message => 'Not authorized to invite new users'
    @role = Role.find(resource_params[:role_id])
    self.resource = User.invite!({ email: resource_params[:email] }, current_inviter) if not @role.nil?

    if resource.errors.empty? and 
       !@role.nil? and
       !self.resource.add_role(@role.name).nil?
      set_flash_message :notice, :send_instructions, :email => self.resource.email
      respond_with resource, :location => after_invite_path_for(resource)
    else
      respond_with_navigational(resource) { render :new }
    end
  end

  def new
    authorize! :create, User, :message => 'Not authorized to invite new users'
    super
  end

  def destroy
    authorize! :destroy, User, :message => 'Not authorized to destroy user invitations'
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, User, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
     authorize! :show, User, :message => 'Not authorized to show user.'
     @user = User.find(params[:id])
  end
  
  def update
    params[:user][:send_notification] = (params[:user][:send_notification] == '1')
    @user = User.find(params[:id])
    authorize! :update, @user, :message => 'Not authorized to edit users.'
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, User, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.roles.delete(user.roles) if !user.roles.nil?
      redirect_to users_path, :notice => "User deactivated."
    else
      redirect_to users_path, :notice => "Can't deactivate yourself."
    end
  end
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Edit User</h3>
    </div>
    <div class="modal-body">
    <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| "#{t.name.titleize}".html_safe}, :label => "Role", checked: user.role_ids.first %>
    <%= f.input :send_notification, :label => "Send email notification when scan added" %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Update", :class => "btn btn-primary" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users
    <%= link_to new_user_invitation_path, 
                            title: "Invite new user",
                            class: "btn" do %>
                  <i class="icon-plus"></i> Add New User
                <% end %>
</h3>

<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.nil? ? "Deactivated" : user.roles.first.name.titleize %></td>
      <td>
        <%= link_to "\#role-options-#{user.id}", 
                    :data => { :toggle => "modal" },
                    :title => "Change role or notifications",
                    :class => 'btn' do %>
          <i class="icon-user"></i>
        <% end %>
        <%= render user %>
      </td>
      <td>
        <% if (user != current_user && ! user.roles.empty?) %>
          <%= link_to user_path(user), 
                      :data => { :confirm => "Are you sure you want to deactivate this user?" }, 
                      :method => :delete, 
                      :title => "Deactivate user",
                      :class => 'btn btn-danger' do %>
            <i class="icon-remove-circle icon-white"></i>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>