config/routes.rb
Scanhandler::Application.routes.draw do
  match "users/inactive" => "root#inactive"
  authenticated :user do
    root :to => 'root#index'
  end
  devise_scope :user do
  	root :to => "devise/sessions#new"
  end
  devise_for :users, :skip => [:registrations], :controllers => { :invitations => 'users/invitations' }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users
  match "people/search" => "people#search"
  resources :people do
    resources :scans, only: [:create, :destroy]
    resources :person_notes, only: [:create, :destroy]
  end
  match "scans/:id" => "scans#download", via: :get, as: :download_scan
  match "scans/:id" => "scans#destroy", via: :delete, as: :destroy_scan
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { maximum: 64 }


  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :send_notification, :as => :admin
  attr_accessible :name, :send_notification, :email, :password, :password_confirmation, :remember_me

  has_many :people
  has_many :scans
  has_many :person_notes
 end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_filter :authenticate_user!

  def after_invite_path_for(resource)
    users_path
  end

  def after_accept_path_for(resource)
    people_path
  end

  def create
    authorize! :create, User, :message => 'Not authorized to invite new users'
    @role = Role.find(resource_params[:role_id])
    self.resource = User.invite!({ email: resource_params[:email] }, current_inviter) if not @role.nil?

    if resource.errors.empty? and 
       !@role.nil? and
       !self.resource.add_role(@role.name).nil?
      set_flash_message :notice, :send_instructions, :email => self.resource.email
      respond_with resource, :location => after_invite_path_for(resource)
    else
      respond_with_navigational(resource) { render :new }
    end
  end

  def new
    authorize! :create, User, :message => 'Not authorized to invite new users'
    super
  end

  def destroy
    authorize! :destroy, User, :message => 'Not authorized to destroy user invitations'
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, User, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
     authorize! :show, User, :message => 'Not authorized to show user.'
     @user = User.find(params[:id])
  end
  
  def update
    params[:user][:send_notification] = (params[:user][:send_notification] == '1')
    @user = User.find(params[:id])
    authorize! :update, @user, :message => 'Not authorized to edit users.'
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, User, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.roles.delete(user.roles) if !user.roles.nil?
      redirect_to users_path, :notice => "User deactivated."
    else
      redirect_to users_path, :notice => "Can't deactivate yourself."
    end
  end
end

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= simple_form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <%= f.input :name %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.submit t("devise.invitations.edit.submit_button"), class: "btn btn-primary" %>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: {method: :post, class: "form-horizontal"} do |f| %>
  <%= devise_error_messages! %>

    <%= f.input :role_id, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| "#{t.name.titleize}".html_safe}, :label => "Role", checked: Role.find_by_name('viewer').id %>
    <%= f.input :email %>

    <div class="control-group">
      <div class="controls">
        <%= f.submit t("devise.invitations.new.submit_button"), class: "btn btn-primary" %>
      </div>
    </div>
<% end %>